package hadad.db.canonicaldb;

import hadad.db.chase.Constraint;

/**
 * Represents a tuple generated by a <code>Constraint</code>.
 */
public class ConstraintTuple extends Tuple {
    /**
     * The <code>Constraint</code> that generated this <code>Tuple</code>.
     */
    protected Constraint constraint;

    /**
     * Constructor
     * 
     * @param size
     *            the tuple size
     * @param constraint
     *            the constraints that generated this tuple
     */
    public ConstraintTuple(final int size, final Constraint constraint) {
        super(size);
        this.constraint = constraint;
    }

}
