/* Generated By:JavaCC: Do not edit this line. RelSchemaParserConstants.java */
package hadad.commons.relationalschema.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RelSchemaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int EOS = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int LBR = 10;
  /** RegularExpression Id. */
  int RBR = 11;
  /** RegularExpression Id. */
  int PIPE = 12;
  /** RegularExpression Id. */
  int PATTERN_NAME = 13;
  /** RegularExpression Id. */
  int RELATION_NAME = 14;
  /** RegularExpression Id. */
  int RELATION_ARITY = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "<PATTERN_NAME>",
    "<RELATION_NAME>",
    "<RELATION_ARITY>",
  };

}
