/* Generated By:JavaCC: Do not edit this line. ConstraintParserConstants.java */
package hadad.commons.constraints.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstraintParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int EOC = 8;
  /** RegularExpression Id. */
  int PREM_SEP = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int EQ = 14;
  /** RegularExpression Id. */
  int RELATION_AND_VARIABLE_NAME = 15;
  /** RegularExpression Id. */
  int STRING_CONSTANT = 16;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"false\"",
    "\"true\"",
    "\";\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\"\"",
    "\"=\"",
    "<RELATION_AND_VARIABLE_NAME>",
    "<STRING_CONSTANT>",
    "<INTEGER_CONSTANT>",
  };

}
