/* Generated By:JavaCC: Do not edit this line. CQParserConstants.java */
package hadad.commons.conjunctivequery.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CQParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int EOQ = 6;
  /** RegularExpression Id. */
  int LANGLE = 7;
  /** RegularExpression Id. */
  int RANGLE = 8;
  /** RegularExpression Id. */
  int RULE_SEP = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int QUERY_AND_PREDICATE_AND_VARIABLE_NAME = 16;
  /** RegularExpression Id. */
  int STRING_CONSTANT = 17;
  /** RegularExpression Id. */
  int INTEGER_CONSTANT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\";\"",
    "\"<\"",
    "\">\"",
    "\":-\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "<QUERY_AND_PREDICATE_AND_VARIABLE_NAME>",
    "<STRING_CONSTANT>",
    "<INTEGER_CONSTANT>",
  };

}
